### ISSUE TITLE
Which MySQLWorkbench version does this plugin support?

### ISSUE THREAD

**Issue by emhlbmc** [meigesir/data_dictionary_for_mysql#1]
My MySQLWorkbench version is 6.3 CE and I installed this plugin, but I didn't see the Tools > Catalog option.

**Comment by meigesir** [comment]
@Lunatictwo 你可能需要先打开一个Model
![a36f5ac1-c849-42c7-8ea2-81316cb9efe2](https://user-images.githubusercontent.com/1229786/40619442-9e755398-62c7-11e8-9202-55a52f3c13a6.png)

**Comment by emhlbmc** [comment]
Thanks.
